services:
  app:
    container_name: kernallab-app
    build: .
    volumes:
      - ./:/app
      - /app/vendor
      - /app/node_modules
    environment:
      - APP_DEBUG=true
    depends_on:
      - database

    # Le serveur Web
  web:
      image: caddy:latest
      container_name: kernallab-web
      ports:
        - "80:80"
      volumes:
        - ./:/app
        - ./caddy/dev/Caddyfile:/etc/caddy/Caddyfile
      depends_on:
        - app

  database:
    container_name: kernellab-database
    env_file:
      - ".env"
    restart: always
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - "./database/mysql-init:/docker-entrypoint-initdb.d"


  phpmyadmin:
    container_name: kernellab-phpmyadmin
    env_file:
      - ".env"
    restart: always
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}

volumes:
  caddy_data:
  caddy_config:
  database_volume:
