services:
  app:
    container_name: kernallab
    build: .
    ports:
      - "80:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  database:
    container_name: kernellab-database
    restart: always
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - ".:/etc/mysql/conf.d"

  phpmyadmin:
    container_name: kernellab-phpmyadmin
    restart: always
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_USER=user
      - PMA_PASSWORD=password
      - PMA_HOST=database
      - PMA_PORT=3306

volumes:
  caddy_data:
  caddy_config:
  database_volume:
