services:
  app:
    container_name: kernallab
    build: .
    ports:
      - "80:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  database:
    container_name: kernellab-database
    env_file:
      - ".env"
    restart: always
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - "./database/mysql-init:/docker-entrypoint-initdb.d"


  phpmyadmin:
    container_name: kernellab-phpmyadmin
    env_file:
      - ".env"
    restart: always
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}

volumes:
  caddy_data:
  caddy_config:
  database_volume:
